### ISSUE TITLE
EDMJR-0006: Remover botões que listam produtos que não são necessários

### ISSUE THREAD

**Issue by Edson-Ivo** [gabrielmaia3/gabrielmaia3.github.io#8]
Remover as 2 listas mostradas nas imagens.

![image](https://user-images.githubusercontent.com/42719020/145111606-9c2a1ff9-3eb4-4fe7-9690-dabfe5a91976.png)

**Comment by ribamarf01** [comment]
#9 Pull Request com as alterações
